// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uysvmntghjkgfggsitmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5c3ZtbnRnaGprZ2ZnZ3NpdG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzUxMzcsImV4cCI6MjA3MjA1MTEzN30.34qmceuSJGJTNTHZ6ivAph1roVkwRPLfoaDZuTFgxSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});